### ISSUE TITLE
Typo? fontisto-famale

### ISSUE THREAD

**Issue by jimmydinamika** [codeat3/blade-fontisto-icons#1]
I think it's should be,

`<x-icon name="fontisto-female" class="h-10 w-10 rounded-full text-gray-200" />`

**Comment by swapnilsarwe** [comment]
that surely is a a typo, but that exists in the original fontisto repo from where we sync the icons.  https://github.com/kenangundogan/fontisto/blob/master/icons/svg/interfaces/famale.svg

But somehow https://fontisto.com/icons shows it correct, I'll give a look if there is any mapping or meta-data related to it in the repo.

**Comment by swapnilsarwe** [comment]
have created a PR for the correction in the original repo #https://github.com/kenangundogan/fontisto/pull/42

**Comment by swapnilsarwe** [comment]
Fixed in the latest commit #https://github.com/codeat3/blade-fontisto-icons/commit/435b442057753818d9f80533f775d75fb2b34850 , kindly update the package to [1.0.1](https://github.com/codeat3/blade-fontisto-icons/releases/tag/1.0.1)
